"""Utility modules for {{ project_name }}.

This package provides reusable utilities for common patterns:
- validation: Input normalization and parameter validation
- responses: Standardized response formatting
- errors: User-friendly error messages with suggestions
{% if include_persistence_helpers -%}
- persistence: State persistence helpers
{% endif -%}
- claude_metrics: Claude AI effectiveness tracking and ROI calculation

Generated by chora-base template.
"""

{% if include_api_utilities -%}
from .validation import normalize_input, InputFormat  # noqa: F401
from .responses import Response  # noqa: F401
from .errors import ErrorFormatter  # noqa: F401
{% endif -%}
{% if include_persistence_helpers -%}
from .persistence import StatefulObject  # noqa: F401
{% endif -%}
from .claude_metrics import ClaudeMetric, ClaudeROICalculator  # noqa: F401

__all__ = [
{% if include_api_utilities -%}
    "normalize_input",
    "InputFormat",
    "Response",
    "ErrorFormatter",
{% endif -%}
{% if include_persistence_helpers -%}
    "StatefulObject",
{% endif -%}
    "ClaudeMetric",
    "ClaudeROICalculator",
]
