apiVersion: chora.dev/v1
kind: Capability
metadata:
  dc_identifier: chora.integration.react_performance
  dc_identifier_legacy: SAP-025
  dc_title: React Performance Optimization
  dc_description: Core Web Vitals optimization with RSC, code splitting, image/font
    optimization, and bundle size limits
  dc_type: Pattern
  dc_hasVersion: 1.0.0
  dc_creator: chora-base
  dc_date: '2025-11-15'
  dc_format: text/markdown
  dc_subject:
  - react
  - performance
  - web-vitals
  - optimization
dc_relation:
  requires:
  - capability: chora.infrastructure.sap_framework
    relationship: prerequisite
  - capability: chora.react.foundation
    relationship: prerequisite
chora_pattern:
  artifacts:
  - type: capability_charter
    path: docs/skilled-awareness/react-performance\capability-charter.md
    format: text/markdown
  - type: protocol_specification
    path: docs/skilled-awareness/react-performance\protocol-spec.md
    format: text/markdown
  - type: awareness_guide
    path: docs/skilled-awareness/react-performance\AGENTS.md
    format: text/markdown
  - type: awareness_guide
    path: docs/skilled-awareness/react-performance\awareness-guide.md
    format: text/markdown
  - type: adoption_blueprint
    path: docs/skilled-awareness/react-performance\adoption-blueprint.md
    format: text/markdown
  - type: adoption_ledger
    path: docs/skilled-awareness/react-performance\ledger.md
    format: text/markdown
