name: Chora CI

on:
  push:
    branches: [ main, "feature/**", "fix/**" ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run validators
        env:
          PYTHONPATH: src
        run: |
          python -m mcp_orchestrator.cli manifest-validate manifests/star.yaml
          python -m mcp_orchestrator.cli behavior-validate docs/capabilities/behaviors
          python -m mcp_orchestrator.cli scenario-validate manifests/star.yaml

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q

